name: Kittygram CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run tests
      run: |
        echo "Running tests..."
    
    - name: Deploy
      run: |
        echo "Deploying..."
