server {
    listen 80;
    server_name localhost;
    client_max_body_size 20M;

    # Прокси для API и админки бэкенда
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Раздача статики и медиа бэкенда (через volume)
    location /static/admin/ {
        alias /backend_static/admin/;
    }
    location /static/rest_framework/ {
        alias /backend_static/rest_framework/;
    }
    location /media/ {
        alias /media/;
    }

    # Прокси для фронтенда
    location / {
        proxy_pass http://frontend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
